CREATE TABLE HELPER_CERTIFICATE(
	HELPER_ID VARCHAR2(50),
	CERTIFICATE VARCHAR2(500),
	DATE_OBTAINED DATE,
	CONSTRAINT FK_CERTIFICATE FOREIGN KEY(HELPER_ID)
	REFERENCES HELPER(HELPER_ID)
);


INSERT ALL INTO HELPER_CERTIFICATE
VALUES('brian', 'TOEFL Certificate', TO_DATE('10/27/2011', 'MM/DD/YYYY'))
INTO HELPER_CERTIFICATE
VALUES('vic', 'Tour Guide Certificate', TO_DATE('04/05/2007', 'MM/DD/YYYY'))
INTO HELPER_CERTIFICATE
VALUES('hamish', 'Scuba Diving Instructing License', TO_DATE('08/16/2010', 'MM/DD/YYYY'))
INTO HELPER_CERTIFICATE
VALUES('emily', 'Certificate of Accounting', TO_DATE('02/27/2007', 'MM/DD/YYYY'))
INTO HELPER_CERTIFICATE
VALUES('sky', 'Real Estate License', TO_DATE('05/13/2012', 'MM/DD/YYYY'))
INTO HELPER_CERTIFICATE
VALUES('nicole', 'Interpretation License', TO_DATE('10/25/2007', 'MM/DD/YYYY'))
SELECT * FROM DUAL;


SELECT * FROM HELPER_CERTIFICATE;


DROP TABLE HELPER_CERTIFICATE;







