CREATE SEQUENCE HELPME_REPLY_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

DROP SEQUENCE HELPME_REPLY_SEQ;

CREATE TABLE HELPME_BOARD_REPLY(
	REPLY_NUM NUMBER(8),
	BOARD_NUM NUMBER(5),
	CLIENT_NO NUMBER(10),
	REPLY_CONTENTS VARCHAR2(4000),
	CONSTRAINT HELPME_REPLY_PK PRIMARY KEY(REPLY_NUM),
	CONSTRAINT HELPME_REPLY_NUM_FK FOREIGN KEY(BOARD_NUM) 
	REFERENCES HELPME_BOARD(BOARD_NUM) ON DELETE CASCADE,
	CONSTRAINT HELPME_REPLY_CLIENT_FK FOREIGN KEY(CLIENT_NO) 
	REFERENCES CLIENT(CLIENT_NO) ON DELETE CASCADE
);

DROP TABLE HELPME_BOARD_REPLY;

SELECT * FROM HELPME_BOARD_REPLY;

SELECT R.*, (SELECT C.CLIENT_ID FROM CLIENT C WHERE R.CLIENT_NO = C.CLIENT_NO) AS CLIENT_ID 
		FROM HELPME_BOARD_REPLY R 
		WHERE BOARD_NUM = 36 ORDER BY REPLY_NUM DESC;

--ALTER TABLE HELPME_BOARD_REPLY ADD CONSTRAINT FK_CLIENT_NO FOREIGN KEY (CLIENT_NO) REFERENCES CLIENT(CLIENT_NO) ON DELETE CASCADE;
		
SELECT B.*, (SELECT C.CLIENT_ID FROM CLIENT C WHERE B.CLIENT_NO = C.CLIENT_NO) AS CLIENT_ID FROM HELPME_BOARD B WHERE B.BOARD_NUM = 36;