CREATE SEQUENCE RESERVATION_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

DROP SEQUENCE RESERVATION_SEQ;

--예약 테이블(RESERVATION)

CREATE TABLE RESERVATION(
	RES_NO NUMBER(10),
	SERVICE VARCHAR2(50),
	DATE_CREATED DATE DEFAULT SYSDATE,
	HELPER_ID VARCHAR2(50),
	CLIENT_NO NUMBER(10),
	MEETING_AREA VARCHAR2(50),
	MEETING_PLACE VARCHAR2(50),
	MEETING_DATE DATE,
	START_TIME NUMBER(3,1),
	END_TIME NUMBER(3,1),
	POINTS_SPENT NUMBER(10), 
	RES_STATUS VARCHAR2(50) DEFAULT 'in progress' NOT NULL,
	CONSTRAINT PK_RES_NO PRIMARY KEY(RES_NO),
	CONSTRAINT FK_RES_CLIENT_NO FOREIGN KEY(CLIENT_NO)
	REFERENCES CLIENT(CLIENT_NO) ON DELETE CASCADE,
	CONSTRAINT FK_RES_HELPER_ID FOREIGN KEY(HELPER_ID)
	REFERENCES HELPER(HELPER_ID)
);

DROP TABLE RESERVATION;

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'brian', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/05', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'brian', 2, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/05', 'YYYY/MM/DD'), 13, 15, 30000);



INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'daniel', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/04', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'daniel', 2, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/04', 'YYYY/MM/DD'), 13, 15, 30000);





INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'grant', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/03', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'joel', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/10', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'natalie', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/11', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'nicole', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'emily', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'joel', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'hamish', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'eric', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'vic', 1, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'traivs', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'charles', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'jesse', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'sky', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'gareth', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'dave', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);

INSERT INTO RESERVATION (RES_NO, SERVICE, HELPER_ID, CLIENT_NO, MEETING_AREA, MEETING_PLACE, MEETING_DATE,
START_TIME, END_TIME, POINTS_SPENT)
VALUES(RESERVATION_SEQ.NEXTVAL, 'translation', 'elliot', 83, 
'Gangnam-gu', 'Gangnam station exit 11',  TO_DATE('2020/11/12', 'YYYY/MM/DD'), 13, 15, 30000);


SELECT * FROM RESERVATION;

SELECT RES_NO FROM (SELECT RES_NO FROM RESERVATION WHERE CLIENT_NO = 62 AND HELPER_ID = 'elliot'
ORDER BY RES_NO DESC) WHERE ROWNUM =1;
--10am ~ 10pm

--10~12, 13~18, 19~20

SELECT HELPER_ID, SUM(END_TIME - START_TIME) FROM 
(SELECT * FROM RESERVATION WHERE START_TIME >= 6 AND END_TIME <= 12 
AND DATE_CREATED = TO_DATE('2020/11/05', 'YYYY/MM/DD'))
GROUP BY HELPER_ID;

SELECT HELPER_ID, SUM(END_TIME - START_TIME) FROM 
(SELECT * FROM RESERVATION WHERE START_TIME >= 13 AND END_TIME <= 18 
AND DATE_CREATED = TO_DATE('2020/11/05', 'YYYY/MM/DD'))
GROUP BY HELPER_ID;

SELECT HELPER_ID, SUM(END_TIME - START_TIME) FROM 
(SELECT * FROM RESERVATION WHERE START_TIME >= 19 AND END_TIME <= 24 
AND DATE_CREATED = TO_DATE('2020/11/05', 'YYYY/MM/DD'))
GROUP BY HELPER_ID;













CREATE TABLE RESERVATION2(
	HELPER_ID VARCHAR2(50),
	START_TIME NUMBER(3,1),
	END_TIME NUMBER(3,1),
	DATE_CREATED DATE
);

DROP TABLE RESERVATION2;

INSERT INTO RESERVATION2 VALUES('B', 6, 6.5, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('B', 6, 6.5, TO_DATE('2020/11/06', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('B', 8, 9, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('B', 13, 15, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('B', 6, 13, TO_DATE('2020/11/05', 'YYYY/MM/DD'));

INSERT INTO RESERVATION2 VALUES('S', 6, 6.5, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('S', 6, 6.5, TO_DATE('2020/11/06', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('S', 8, 9, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('S', 13, 15, TO_DATE('2020/11/05', 'YYYY/MM/DD'));
INSERT INTO RESERVATION2 VALUES('S', 6, 13, TO_DATE('2020/11/05', 'YYYY/MM/DD'));

INSERT INTO RESERVATION2 VALUES('S', 13, 15, TO_DATE('2020/11/05', 'YYYY/MM/DD'));



SELECT * FROM RESERVATION2;

SELECT HELPER_ID, SUM(END_TIME - START_TIME) FROM 
(SELECT * FROM RESERVATION2 WHERE START_TIME >= 6 AND END_TIME <= 12 
AND DATE_CREATED = TO_DATE('2020/11/05', 'YYYY/MM/DD'))
GROUP BY HELPER_ID;




