



CREATE TABLE RATING_CNT(
	HELPER_ID VARCHAR2 (50),
	CLIENT_NO NUMBER (10),
	RATE_CNT NUMBER(1) DEFAULT 0,
	CONSTRAINT FK_RATING_CNT_HELPER FOREIGN KEY(HELPER_ID)
	REFERENCES HELPER(HELPER_ID),
	CONSTRAINT FK_RATING_CNT_CLIENT FOREIGN KEY(CLIENT_NO)
	REFERENCES CLIENT(CLIENT_NO) ON DELETE CASCADE

);

DROP TABLE RATING_CNT;

SELECT * FROM RATING_CNT;